language: perl
os:
  - linux
  - osx
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - AUTOMATED_TESTING=1
install:
  - cpanm --quiet Text::CSV_XS            || true
  - cpanm --quiet Spreadsheet::ReadSXC    || true
  - cpanm --quiet Spreadsheet::ParseExcel || true
notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
