language: perl
os:
  - linux
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - AUTOMATED_TESTING=1
before_install:
  - brew install cpanm                              || true
install:
  - cpanm --quiet Test::More                        || true
  - cpanm --quiet Test::NoWarnings                  || true
  - cpanm --quiet Data::Peek                        || true
  - cpanm --quiet Text::CSV_XS                      || true
  - cpanm --quiet Text::CSV                         || true
  - cpanm --quiet Spreadsheet::ReadSXC              || true
  - cpanm --quiet Spreadsheet::ParseExcel           || true
  - cpanm --quiet Spreadsheet::ParseXLSX            || true
  - cpanm --quiet Spreadsheet::XLSX                 || true
  - cpanm --quiet Spreadsheet::XLSX::Reader::LibXML || true
notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
