language: perl
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - AUTOMATED_TESTING=1
install:
  - cpanm --quiet Text::CSV_XS Spreadsheet::ReadSXC Spreadsheet::ParseExcel Spreadsheet::ParseXLSX
